// <auto-generated />
namespace TelstarLogistics.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modify_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_address));
        
        string IMigrationMetadata.Id
        {
            get { return "202110150304029_modify_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
